export const yelpStars = {
  android: {
    hdpi: {
      '0': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_0.png',
      '1': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_1.png',
      '2': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_2.png',
      '3': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_3.png',
      '4': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_4.png',
      '5': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_5.png',
      '1.5': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_1_half.png',
      '2.5': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_2_half.png',
      '3.5': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_3_half.png',
      '4.5': './assets/yelp_stars/android/drawable-hdpi/large/stars_large_4_half.png',
    },
    xhdpi: {
      '0': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_0.png',
      '1': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_1.png',
      '2': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_2.png',
      '3': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_3.png',
      '4': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_4.png',
      '5': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_5.png',
      '1.5': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_1_half.png',
      '2.5': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_2_half.png',
      '3.5': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_3_half.png',
      '4.5': './assets/yelp_stars/android/drawable-xhdpi/large/stars_large_4_half.png',
    },
    xxhdpi: {
      '0': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_0.png',
      '1': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_1.png',
      '2': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_2.png',
      '3': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_3.png',
      '4': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_4.png',
      '5': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_5.png',
      '1.5': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_1_half.png',
      '2.5': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_2_half.png',
      '3.5': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_3_half.png',
      '4.5': './assets/yelp_stars/android/drawable-xxhdpi/large/stars_large_4_half.png',
    },
  },
  ios: {
    _: {
      '0': './assets/yelp_stars/web_and_ios/large/large_0.png',
      '1': './assets/yelp_stars/web_and_ios/large/large_1.png',
      '2': './assets/yelp_stars/web_and_ios/large/large_2.png',
      '3': './assets/yelp_stars/web_and_ios/large/large_3.png',
      '4': './assets/yelp_stars/web_and_ios/large/large_4.png',
      '5': './assets/yelp_stars/web_and_ios/large/large_5.png',
      '1.5': './assets/yelp_stars/web_and_ios/large/large_1_half.png',
      '2.5': './assets/yelp_stars/web_and_ios/large/large_2_half.png',
      '3.5': './assets/yelp_stars/web_and_ios/large/large_3_half.png',
      '4.5': './assets/yelp_stars/web_and_ios/large/large_4_half.png',
    },
  },
}
